### ISSUE TITLE
simple_logger v1.12.0 fails to build with chrono feature and default_features = false

### ISSUE THREAD

**Issue by amoskvin** [borntyping/rust-simple_logger#35]
The new version fails with this combination of features. It worked with v1.11.0.
```
$ cat Cargo.toml
[package]
name = "sltest"
version = "0.1.0"
edition = "2018"

[dependencies.simple_logger]
version = "1"
default_features = false
features = ["chrono"]

$ cargo +stable build
   Compiling simple_logger v1.12.0
error[E0609]: no field `colors` on type `SimpleLogger`
   --> /home/alec/.cargo/registry/src/github.com-1ecc6299db9ec823/simple_logger-1.12.0/src/lib.rs:226:14
    |
226 |         self.colors = colors;
    |              ^^^^^^ unknown field
    |
    = note: available fields are: `default_level`, `module_levels`, `timestamps`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0609`.
error: could not compile `simple_logger`

To learn more, run the command again with --verbose.
```

**Comment by borntyping** [comment]
Fix and released in [1.12.1](https://github.com/borntyping/rust-simple_logger/releases/tag/v1.12.1). Thanks @amoskvin and @creekorful!

**Comment by borntyping** [comment]
UTC timestamps are now the default in [simple_logger 2.0.0](https://github.com/borntyping/rust-simple_logger/releases/tag/v2.0.0).
